#!/usr/bin/env python3
"""Generate migrations/009_chart_of_accounts.sql from an accountant's workbook ("Saskaitu planas" sheet).

Usage: python3 scripts/chart-from-xlsx.py Buhalterija.xlsm [UAB|MB|VSI|UKIO] > migrations/009_chart_of_accounts.sql
Rows: A=legal form, C/D=class, E/F=group (2 digits), G/H=sub-group (3 digits), I/J=account (4 digits).
Posting accounts are the deepest level present: a 4-digit account, else a 3-digit group without children.
"""
import sys, collections
import openpyxl

src, form = sys.argv[1], (sys.argv[2] if len(sys.argv) > 2 else 'UAB')
wb = openpyxl.load_workbook(src, read_only=True, data_only=True)
nodes = collections.OrderedDict()  # code -> [name, parent, level]

def clean(s):
    return ' '.join(str(s).replace('Kitõs', 'Kitos').replace('(–)', '(-)').replace('(−)', '(-)').replace('suvetinė', 'suvestinė').split())

def add(code, name, parent, level):
    if code is None or name in (None, ''):
        return
    code = str(int(code))
    if code not in nodes:
        nodes[code] = [clean(name).capitalize() if level == 1 else clean(name), parent, level]

for r in wb['Saskaitu planas'].iter_rows(values_only=True):
    if r[0] != form:
        continue
    add(r[2], r[3], None, 1)
    add(r[4], r[5], str(r[2]), 2)
    add(r[6], r[7], str(r[4]), 3)
    add(r[8], r[9], str(r[6]) if r[6] else str(r[4]), 4)

has_children = {p for (_, p, _) in nodes.values() if p}
TYPE = {'1': 'asset', '2': 'asset', '3': 'equity', '4': 'liability', '5': 'revenue', '6': 'expense'}

def subtype(code):
    if code[0] == '1': return 'noncurrent'
    if code.startswith('20'): return 'inventory'
    if code.startswith('241'): return 'receivable'
    if code.startswith('27'): return 'cash'
    if code[0] == '2': return 'current'
    if code.startswith('42'): return 'noncurrent'
    if code.startswith('443'): return 'payable'
    if code[0] == '4': return 'current'
    if code.startswith('60'): return 'cogs'
    return ''

q = lambda s: "'" + s.replace("'", "''") + "'"
print(f"-- Chart of accounts generated by scripts/chart-from-xlsx.py from the accountant's workbook ({form} chart).")
print("INSERT INTO new_chart(code, name, type, subtype, parent_code, level, postable) VALUES")
rows = []
for code, (name, parent, level) in nodes.items():
    rows.append(f" ({q(code)},{q(name)},{q(TYPE[code[0]])},{q(subtype(code))},{q(parent) if parent else 'NULL'},{level},{'false' if code in has_children else 'true'})")
print(',\n'.join(rows) + ';')
